# Generated by Django 3.1.3 on 2021-04-10 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userNo', models.AutoField(db_column='userNo', primary_key=True, serialize=False)),
                ('userName', models.CharField(blank=True, db_column='userName', max_length=50)),
                ('createDate', models.DateField(db_column='createDate', default=django.utils.timezone.now)),
                ('mailAddress', models.CharField(blank=True, db_column='mailAddress', max_length=50)),
                ('authorityValue', models.IntegerField(db_column='authorityValue', default=0)),
                ('userState', models.BooleanField(db_column='userState', default=True)),
                ('userPassword', models.CharField(db_column='userPassword', max_length=32)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('mailNo', models.AutoField(db_column='mailNo', primary_key=True, serialize=False)),
                ('receiver', models.CharField(blank=True, db_column='receive', max_length=200)),
                ('sender', models.CharField(blank=True, db_column='sender', max_length=200)),
                ('subject', models.CharField(blank=True, db_column='subject', max_length=200)),
                ('copy', models.CharField(blank=True, db_column='copy', max_length=200)),
                ('isRead', models.BooleanField(db_column='isRead', default=False)),
                ('isServed', models.IntegerField(db_column='authorityValue', default=0)),
                ('content', models.CharField(blank=True, db_column='content', max_length=500)),
                ('rendOrReceiptDate', models.DateField(db_column='rendOrReceiptDate', default=django.utils.timezone.now)),
                ('userNo', models.ForeignKey(db_column='userNo', default='1', on_delete=django.db.models.deletion.CASCADE, to='WebMail.users')),
            ],
            options={
                'db_table': 'Mails',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contactNo', models.AutoField(db_column='contactNo', primary_key=True, serialize=False)),
                ('contactName', models.CharField(db_column='userName', max_length=50)),
                ('tel', models.CharField(blank=True, db_column='tel', max_length=50)),
                ('mailAddress', models.CharField(blank=True, db_column='mailAddress', max_length=50)),
                ('userNo', models.ForeignKey(db_column='userNo', default='1', on_delete=django.db.models.deletion.CASCADE, to='WebMail.users')),
            ],
            options={
                'db_table': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('attachmentNo', models.AutoField(db_column='attachmentNo', primary_key=True, serialize=False)),
                ('attachmentName', models.CharField(db_column='attachmentName', max_length=100)),
                ('savedAddress', models.CharField(db_column='savedAddress', max_length=200)),
                ('attachmentSize', models.FloatField(db_column='attachmentSize')),
                ('mailNo', models.ForeignKey(db_column='mailNo', default='1', on_delete=django.db.models.deletion.CASCADE, to='WebMail.mails')),
            ],
            options={
                'db_table': 'Attachments',
            },
        ),
    ]
