# Generated by Django 3.1.3 on 2021-05-16 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='subject',
            field=models.CharField(db_column='subject', default='无主题', max_length=500),
        ),
        migrations.AlterField(
            model_name='users',
            name='createDate',
            field=models.DateField(db_column='createDate', default=datetime.date(2021, 5, 16)),
        ),
    ]
