# Generated by Django 3.1.3 on 2021-04-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mails',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='mails',
            name='userNo',
        ),
        migrations.AddField(
            model_name='mails',
            name='ip',
            field=models.CharField(db_column='ip', default='127.0.0.1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mailAddress',
            field=models.CharField(db_column='mailAddress', max_length=50),
        ),
        migrations.AlterField(
            model_name='mails',
            name='content',
            field=models.CharField(db_column='content', default='内容为空', max_length=500),
        ),
        migrations.AlterField(
            model_name='mails',
            name='isRead',
            field=models.IntegerField(db_column='isRead', default=0),
        ),
        migrations.AlterField(
            model_name='mails',
            name='isServed',
            field=models.IntegerField(db_column='isServed', default=0),
        ),
        migrations.AlterField(
            model_name='mails',
            name='receiver',
            field=models.CharField(db_column='receive', max_length=200),
        ),
        migrations.AlterField(
            model_name='mails',
            name='sender',
            field=models.CharField(db_column='sender', max_length=200),
        ),
        migrations.AlterField(
            model_name='mails',
            name='subject',
            field=models.CharField(db_column='subject', default='未命名的主题', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='mailAddress',
            field=models.CharField(db_column='mailAddress', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='userName',
            field=models.CharField(db_column='userName', default='未命名', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='userState',
            field=models.IntegerField(db_column='userState', default=1),
        ),
    ]
