# Generated by Django 3.1.3 on 2021-05-16 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebMail', '0002_auto_20210516_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='rendOrReceiptDate',
            field=models.DateTimeField(db_column='rendOrReceiptDate', default=django.utils.timezone.now),
        ),
    ]
