# Generated by Django 3.1.3 on 2021-04-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMail', '0003_auto_20210412_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='receiver',
            field=models.CharField(db_column='receiver', max_length=200),
        ),
    ]
